using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccessLayer
{
    public partial class RWprole
    {
        public long ChId { get; set; }
        public int WproleId { get; set; }
        public string WproleName { get; set; }
        public int MenuId { get; set; }
        public int DefaultMenuId { get; set; }
        public string Notes { get; set; }
        public int ProcessingId { get; set; }
        public bool AllowInvalidMonExp { get; set; }
        public bool AllowQtyReduction { get; set; }
        public bool AlwaysShowPosEditor { get; set; }
        public bool AskDcardsAfterOpen { get; set; }
        public bool? AskDcardsBeforeClose { get; set; }
        public bool AskParamsAfterOpen { get; set; }
        public bool? AskParamsBeforeClose { get; set; }
        public bool AskPwdanull { get; set; }
        public bool AskPwdbalance { get; set; }
        public bool AskPwdcn { get; set; }
        public bool AskPwdcnCheque { get; set; }
        public bool? AskPwddcardFind { get; set; }
        public bool AskPwddeposit { get; set; }
        public bool AskPwdfind { get; set; }
        public bool AskPwdmoneyBox { get; set; }
        public bool AskPwdperiodRep { get; set; }
        public bool AskPwdposRePay { get; set; }
        public bool AskPwdret { get; set; }
        public bool AskPwdsuspend { get; set; }
        public bool AskPwdOnMore { get; set; }
        public bool AskPwdOnExit { get; set; }
        public bool AskVisitorsAfterOpen { get; set; }
        public bool AsyncChequeInput { get; set; }
        public bool AutoFillPays { get; set; }
        public bool? AutoSelDiscs { get; set; }
        public bool? CancelMdiscsWarning { get; set; }
        public bool CanEditPrice { get; set; }
        public bool CanEditProdId { get; set; }
        public bool CanEditWeightQty { get; set; }
        public bool? CanEnterCodeId1 { get; set; }
        public bool? CanEnterCodeId2 { get; set; }
        public bool? CanEnterCodeId3 { get; set; }
        public bool? CanEnterCodeId4 { get; set; }
        public bool? CanEnterCodeId5 { get; set; }
        public bool? CanEnterDcard { get; set; }
        public bool? CanEnterNotes { get; set; }
        public bool CanEnterPosDiscount { get; set; }
        public bool? ChangeSumWarning { get; set; }
        public bool CheckRetPayForms { get; set; }
        public bool? CheckRetSum { get; set; }
        public bool ChequeEmp { get; set; }
        public bool? DecQtyFromRef { get; set; }
        public bool LoginByAdmin { get; set; }
        public decimal MaxChange { get; set; }
        public byte MaxSuspended { get; set; }
        public bool? MixedPays { get; set; }
        public bool? NoManualDcardEnter { get; set; }
        public bool OpenMoneyBoxOnDeposit { get; set; }
        public int PosEmpId { get; set; }
        public int PosEmpIdtype { get; set; }
        public bool PreviewReport { get; set; }
        public bool? PrintAfterSendOrder { get; set; }
        public bool PrintCopyForCard { get; set; }
        public bool PrintDiscs { get; set; }
        public bool PrintInfoAnull { get; set; }
        public string PrintReport { get; set; }
        public string PrintReportMonExp { get; set; }
        public string PrintReportMonRec { get; set; }
        public string PrintReportRet { get; set; }
        public string PrintReportX { get; set; }
        public string PrintReportZ { get; set; }
        public bool PrintTextAnull { get; set; }
        public bool? ShowCancels { get; set; }
        public bool? ShowChequeDisc { get; set; }
        public bool? ShowPosDisc { get; set; }
        public bool? ShowPosEditOnCancel { get; set; }
        public bool? UseBarCode { get; set; }
        public bool UseDecQtyBarCode { get; set; }
        public bool UseEmps { get; set; }
        public bool ZrepAfterShift { get; set; }
        public bool ZrepExecInTime { get; set; }
        public DateTime? ZrepExecTime { get; set; }
        public bool ZreportWarning { get; set; }
        public DateTime? ZrepShiftEndTime { get; set; }
        public int ZrepShiftTimeCheck { get; set; }
        public bool? LoadLinkedMenus { get; set; }
        public bool? LoadProdHints { get; set; }
        public bool? ResetQtyAfterProdAdd { get; set; }
        public bool DriveMode { get; set; }
        public bool PrintRetCopy { get; set; }
        public bool RequireExp { get; set; }
        public bool RequireFullExp { get; set; }
        public bool RequireRec { get; set; }
        public bool ExtendedChequeStates { get; set; }
        public int DiscountMode { get; set; }
        public bool PrintBillRequired { get; set; }
        public string PrintShiftCloseReport { get; set; }
        public string PrintBillReportDraft { get; set; }
        public string PrintBillReport { get; set; }
        public bool UseProdImages { get; set; }
        public bool? CradminRunShift { get; set; }
        public bool? CradminEditPbill { get; set; }
        public string OrderReports { get; set; }
        public int CompletedChequesCount { get; set; }
        public bool ShowProdNotes { get; set; }
        public bool ShowNoChangeButton { get; set; }
        public bool? UseNewMenu { get; set; }
        public bool? AllowManualPasswordInput { get; set; }
        public bool? UseAnullReasons { get; set; }
        public bool RecalcDiscsAfterMods { get; set; }
        public bool? ShowClosedCheques { get; set; }
        public string PrintClientReport { get; set; }
        public bool? AllowVenEditQty { get; set; }
        public string PrintVenReport { get; set; }
        public bool? AllowPeriodicReports { get; set; }
        public DateTime? BookingTimeRulerBegin { get; set; }
        public DateTime? BookingTimeRulerEnd { get; set; }
        public bool BookingUseExtChequeParams { get; set; }
        public int BookingDefaultClientId { get; set; }
        public int BookingOpenWorkHours { get; set; }
        public bool ShowMonNotes { get; set; }
        public bool UsePrintMonitor { get; set; }
        public bool DisplayPrintErrors { get; set; }
        public int PrintMonitorTimeout { get; set; }
        public bool UseSaleTouchMode { get; set; }
        public DateTime ZrepShiftStartTime { get; set; }
        public int ZrepWarningTime { get; set; }
        public int ZrepWarningPeriod { get; set; }
        public bool ZrepBlockExit { get; set; }
        public bool? ZrepShiftBlock { get; set; }
        public bool? AutoZrepBalanceCheck { get; set; }
        public bool? ShowSuspendedChequesPanel { get; set; }
        public bool? ShowClosedChequesPanel { get; set; }
        public bool ShowUniInput { get; set; }
        public int CrchequeFontSize { get; set; }
        public int CrchequeCopiesCount { get; set; }
        public bool? PrintCrname { get; set; }
        public bool PrintPosunionChequeFirst { get; set; }
        public int? CrunionChequeFontSize { get; set; }
        public bool? AllowVen { get; set; }
        public int? CrchequeFontSizeReport { get; set; }
        public string ApiServerParams { get; set; }
        public bool ApiServerGetRets { get; set; }
    }
}
